name: Deployment

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  UNIT: chatgpt-bot.service
  WORKDIR: /home/ec2-user/chatgpt-bot

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.18.x]
        os: [linux]
        arch: [arm64]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o chatgpt-bot ./cmd/main.go

      - uses: actions/upload-artifact@v3
        with:
          name: chatgpt-bot
          path: chatgpt-bot

  deploy:
    needs: build

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: chatgpt-bot

      - name: Add executable permission
        run: chmod +x chatgpt-bot

      - name: Create .env file
        run: |
          echo TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} > .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo VALID_CHAT_ID=${{ vars.VALID_CHAT_ID }} >> .env
          echo STORE_TYPE=redis >> .env

      - name: Stop and disable service
        continue-on-error: true
        run: |
          sudo systemctl stop ${{ env.UNIT }}
          sudo systemctl disable ${{ env.UNIT }}
          sudo systemctl reset-failed ${{ env.UNIT }}

      - name: Copy files
        run: |
          sudo mkdir -p ${{ env.WORKDIR }}
          sudo cp chatgpt-bot ${{ env.WORKDIR }}
          sudo cp .env ${{ env.WORKDIR }}
          sudo cp ${{ env.UNIT }} /etc/systemd/system

      - name: Start service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable ${{ env.UNIT }}
          sudo systemctl start ${{ env.UNIT }}
